---
defaults: &defaults
  working_directory: /tmp/build
  environment:
    IMAGE_NAME: performance-test-demo
    GOOGLE_PROJECT_NAME_DEVELOPMENT: mycujoo-development
    GOOGLE_CLUSTER_NAME_DEVELOPMENT: mycujoo-kubernetes-development
    GOOGLE_COMPUTE_ZONE_DEVELOPMENT: europe-west3-a
    DEBIAN_FRONTEND: noninteractive
    APPLICATION_PORT: 3000
    VERSION: 1.0

version: 2

jobs:
  kd_build_test_deploy:
    <<: *defaults
    docker:
      - image: mycujoo/gcloud-docker:latest
    steps:
      ### Configure environment and set up ###
      - checkout
      - setup_remote_docker
      - run:
          name: Install kube-deploy
          command: |
            wget https://s3.eu-central-1.amazonaws.com/binary-distribution/kube-deploy-linux-amd64 -O /usr/local/bin/kube-deploy
            chmod +x /usr/local/bin/kube-deploy
      - run:
          name: Configure environment and docker login
          command: |
            . kubernetes/configure.sh
            docker login -u _json_key -p "$(cat /root/gcp-key.json)" https://eu.gcr.io
      ### kube-deploy steps start ###
      - run:
          name: Build image and test
          command: |
            docker-compose --version
            kube-deploy build --force-push-image
      - run:
          name: Deploy to kubernetes
          command: |
            echo "Now we deploy!"

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - kd_build_test_deploy:
          context: org-global
