---
defaults: &defaults
  working_directory: /tmp/build
  environment:
    IMAGE_NAME: performance-test-demo
    APPLICATION_PORT: 3000
    VERSION: 1.0

version: 2

jobs:
  kd_build_test_deploy:
    <<: *defaults
    docker:
      - image: mycujoo/gcloud-docker:latest
    steps:
      ### Configure environment and set up ###
      - checkout
      - setup_remote_docker
      - run:
          name: "Build container and run the container"
          command: |
            docker build -t mycujoo/performance-test-demo .
            docker run -d -p 3000:3000 mycujoo/performance-test-demo
      - run:
          name: Run performance tests
          command: |
            docker run --rm  thecodeassassin/alpine-load-tester -n 10 --json-output http://localhost:3000/slow/200 | jq -e -r '.avg < 0.25'
            docker run --rm  thecodeassassin/alpine-load-tester -n 10 --json-output http://localhost:3000/slow/300 | jq -e -r '.avg < 0.35'
            docker run --rm  thecodeassassin/alpine-load-tester -n 10 --json-output http://localhost:3000/slow/500 | jq -e -r '.avg < 0.55'
            docker run --rm  thecodeassassin/alpine-load-tester -n 10 --json-output http://localhost:3000/new | jq -e -r '.avg < 0.2'
      - run:
          name: Deploy to kubernetes
          command: |
            echo "Now we deploy!"

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - kd_build_test_deploy:
          context: org-global
